export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  USER = "USER",
}

export enum RoleGestionnaire {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  RESPONSABLE_POINT_DE_VENTE = "RESPONSABLE_POINT_DE_VENTE",
  RESPONSABLE_COMMUNAUTE = "RESPONSABLE_COMMUNAUTE",
  REVENDEUR = "REVENDEUR",
  AGENT_LOGISTIQUE_APPROVISIONNEMENT = "AGENT_LOGISTIQUE_APPROVISIONNEMENT",
  MAGAZINIER = "MAGAZINIER",
  CAISSIER = "CAISSIER",
  COMMERCIAL = "COMMERCIAL",
  COMPTABLE = "COMPTABLE",
  AUDITEUR_INTERNE = "AUDITEUR_INTERNE",
  RESPONSABLE_VENTE_CREDIT = "RESPONSABLE_VENTE_CREDIT",
  CONTROLEUR_TERRAIN = "CONTROLEUR_TERRAIN",
  AGENT_TERRAIN = "AGENT_TERRAIN",
  RESPONSABLE_ECONOMIQUE = "RESPONSABLE_ECONOMIQUE",
  RESPONSABLE_MARKETING = "RESPONSABLE_MARKETING",
  ACTIONNAIRE = "ACTIONNAIRE",
}
