export enum TransactionType {
  DEPOT = "DEPOT",
  RETRAIT = "RETRAIT",
  COTISATION = "COTISATION",
  TONTINE = "TONTINE",
  REMBOURSEMENT_CREDIT = "REMBOURSEMENT_CREDIT",
  CREDIT = "CREDIT",
  ACHAT = "ACHAT",
  ANNULATION = "ANNULATION",
  VENTE = "VENTE",
}

export enum TypePaiement {
  WALLET_GENERAL = "WALLET_GENERAL",
  WALLET_TONTINE = "WALLET_TONTINE",
  WALLET_CREDIT = "WALLET_CREDIT",
  EXTERNE = "EXTERNE",
  ESPECES = "ESPECES",
  VIREMENT = "VIREMENT",
  CHEQUE = "CHEQUE",
  MOBILE_MONEY = "MOBILE_MONEY",
}
