export enum TypeDocument {
  BILAN = "BILAN",
  COMPTE_RESULTAT = "COMPTE_RESULTAT",
  RAPPORT_ANNUEL = "RAPPORT_ANNUEL",
  PV_AG = "PV_AG",
  CONVOCATION = "CONVOCATION",
  RAPPORT_AUDIT = "RAPPORT_AUDIT",
  STATUTS = "STATUTS",
  PLAN_STRATEGIQUE = "PLAN_STRATEGIQUE",
  AUTRE = "AUTRE",
}

export enum PrioriteNotification {
  URGENT = "URGENT",
  HAUTE = "HAUTE",
  NORMAL = "NORMAL",
}
